import { AlertTriangle, BarChart3, CalendarDays, Check, CheckCircle2, Clock3, Copy, Crown, Globe2, Images, MessageCircleMore, Puzzle, QrCode, ReceiptText, ShieldCheck, Sparkles, WalletCards } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { useLocation } from 'react-router-dom';
import { ErrorState, LoadingState } from '../../components/ui/AsyncState';
import { useStore } from '../../contexts/StoreContext';
import { useToast } from '../../contexts/ToastContext';
import { billingApi, type StoreBillingOverview } from '../../services/billingApi';
import { platformApi } from '../../services/platformApi';
import type { Plan, SubscriptionCharge, SubscriptionPayment } from '../../types';
import { currency } from '../../utils/format';
import { planHasFeature } from '../../utils/plan';
import { buildPixCopyPasteWithAmount, buildStaticPixCopyPaste } from '../../utils/pix';
import { getBillingVisualStatus } from '../../utils/billingStatus';
import { trackInteraction } from '../../services/interactionTelemetry';

const copy=async(value:string)=>{if(value)await navigator.clipboard.writeText(value)};
const dateBr=(value?:string)=>value?new Date(`${value.slice(0,10)}T12:00:00`).toLocaleDateString('pt-BR'):'—';
const dateTimeBr=(value?:string)=>value?new Date(value).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):'—';
const BILLING_WARNING_DAYS=7;
const paymentStatusLabel=(status:SubscriptionPayment['status'])=>({pending:'Aguardando pagamento',proof_sent:'Comprovante enviado',paid:'Pago',rejected:'Não renovado',expired:'Vencido',cancelled:'Cancelado',refunded:'Estornado'}[status]||status);

const planCopy:Record<string,{headline:string;description:string;bullets:string[]}>= {
  ESSENTIAL:{headline:'Seu cardápio profissional, sem complicação',description:'Para sair do PDF e começar a receber pedidos organizados pelo WhatsApp.',bullets:['Cardápio online + checkout','Pedidos gravados antes do WhatsApp','Delivery e retirada','1 foto por produto']},
  STARTER:{headline:'Profissionalize a operação e enxergue o resultado',description:'Tudo do Essencial com Analytics, Financeiro e recursos para uma operação em crescimento.',bullets:['Tudo do Essencial','Analytics e conversão','Financeiro de entradas e saídas','Leitura assistida de nota, cupom e boleto','Banners personalizados']},
  PROFESSIONAL:{headline:'Mais capacidade para uma operação consolidada',description:'Tudo do Profissional com maior capacidade, domínio próprio e suporte prioritário.',bullets:['Tudo do Profissional','Produtos sem limite','Até 10 fotos por produto','Domínio próprio','Suporte prioritário']},
};

export default function AdminPlan(){
  const{settings,planUsage}=useStore();const{showToast}=useToast();const location=useLocation();
  const[plans,setPlans]=useState<Plan[]>([]);const[overview,setOverview]=useState<StoreBillingOverview|null>(null);const[charge,setCharge]=useState<SubscriptionCharge|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[busy,setBusy]=useState('');const[proofOpened,setProofOpened]=useState(false);

  const loadOverview=async()=>{try{setOverview(await billingApi.getOverview(settings.id))}catch{/* o restante da pagina continua utilizavel */}};
  useEffect(()=>{let active=true;Promise.all([platformApi.listPlans(),billingApi.getOverview(settings.id)]).then(([rows,o])=>{if(active){setPlans(rows.filter((p)=>p.active&&p.code!=='DEMO'));setOverview(o)}}).catch((e)=>{if(active)setError(e instanceof Error?e.message:'Não foi possível carregar plano e cobrança.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[settings.id]);

  const sorted=useMemo(()=>[...plans].sort((a,b)=>(a.sortOrder||0)-(b.sortOrder||0)),[plans]);
  const pixCode=useMemo(()=>{if(!charge?.billing)return '';try{const base=charge.payment.pixPayload||charge.billing.pixCopyPaste;if(base)return buildPixCopyPasteWithAmount(base,charge.payment.amount);if(charge.billing.pixKey)return buildStaticPixCopyPaste({key:charge.billing.pixKey,receiver:charge.billing.pixHolderName,city:charge.billing.pixCity||'Linhares',amount:charge.payment.amount,txid:charge.payment.id.replace(/-/g,'').slice(0,25)});return ''}catch{return ''}},[charge]);
  const isPlanChange=Boolean(charge&&(charge.payment.paymentIntent==='plan_change'||charge.plan.id!==planUsage.plan.id));
  const subscription=overview?.subscription;
  const lastPaid=subscription?.lastPayment||overview?.payments.find((payment)=>payment.status==='paid');
  const lastRejected=overview?.payments.find((payment)=>payment.status==='rejected');
  const billingStatus=getBillingVisualStatus({billingState:subscription?.billingState,nextDueDate:subscription?.nextDueDate,dueDay:subscription?.dueDay,warningDays:BILLING_WARNING_DAYS});
  const daysToDue=billingStatus.daysToDue;
  const overdue=billingStatus.overdue;
  const dueSoon=billingStatus.dueSoon;
  const healthClass=`is-${billingStatus.level==='hidden'?'current':billingStatus.level}`;
  const healthTitle=billingStatus.label||'Mensalidade';

  const generate=async(plan:Plan)=>{const changing=plan.id!==planUsage.plan.id&&plan.code!==planUsage.plan.code;setBusy(plan.id);setCharge(null);setProofOpened(false);try{const result=await trackInteraction('subscription_charge_create',()=>billingApi.createManualCharge(settings.id,plan.id),{storeId:settings.id});setCharge(result);await loadOverview();showToast(changing?'Cobrança para alteração de plano gerada.':'Cobrança PIX gerada.','success')}catch(e){showToast(e instanceof Error?e.message:'Não foi possível gerar a cobrança.','error')}finally{setBusy('')}};
  const openProofWhatsApp=()=>{if(!charge?.billing)return;const phone=(charge.billing.whatsapp||'').replace(/\D/g,'');if(!phone){showToast('O WhatsApp de cobrança ainda não foi configurado pelo Admin Master.','error');return}const intent=isPlanChange?`alterar meu plano de ${planUsage.plan.name} para ${charge.plan.name}`:`renovar o plano ${charge.plan.name}`;const text=encodeURIComponent(`Olá! Realizei o pagamento da mensalidade FoodWeb e gostaria de ${intent}.\n\nLoja: ${settings.name}\nValor: ${currency.format(charge.payment.amount)}\nCobrança: ${charge.payment.id}\n\nEstou enviando o comprovante do PIX nesta conversa.`);window.open(`https://wa.me/${phone}?text=${text}`,'_blank','noopener,noreferrer');setProofOpened(true)};
  const confirmProofSent=async()=>{if(!charge)return;try{const payment=await trackInteraction('subscription_proof_sent',()=>billingApi.markProofSent(charge.payment.id),{storeId:settings.id});setCharge({...charge,payment});await loadOverview();showToast('Comprovante marcado como enviado. Aguardando conferência do Admin Master.','success')}catch(e){showToast(e instanceof Error?e.message:'Não foi possível registrar o envio do comprovante.','error')}};

  useEffect(()=>{if(location.hash!=='#vencimento'||!overview)return;window.setTimeout(()=>document.getElementById('vencimento')?.scrollIntoView({behavior:'smooth',block:'start'}),40)},[location.hash,overview]);

  if(loading)return <LoadingState label="Carregando planos..."/>;if(error)return <ErrorState message={error}/>;
  return <>
    <div className="admin-page-title subscription-heading"><div><span className="eyebrow">ASSINATURA FOODWEB</span><h1>Meu plano e mensalidade</h1><p>Consulte vencimento, último pagamento e renove ou altere o plano usando PIX.</p></div><div className="current-plan-pill"><Crown size={17}/><span>Plano atual</span><strong>{planUsage.plan.name}</strong></div></div>

    {subscription&&subscription.billingState!=='trial'&&<section id="vencimento" className={`admin-card food-billing-health-v047 ${healthClass}`}>{overdue?<AlertTriangle size={25}/>:dueSoon?<Clock3 size={25}/>:<CheckCircle2 size={25}/>}<div><span className="eyebrow">SITUAÇÃO DA MENSALIDADE</span><h2>{healthTitle}</h2><p>{overdue?`O vencimento de ${dateBr(subscription.nextDueDate)} ainda não possui renovação confirmada.`:dueSoon?(daysToDue===0?`A mensalidade vence hoje, ${dateBr(subscription.nextDueDate)}.`:`Faltam ${daysToDue} dia(s) para o vencimento de ${dateBr(subscription.nextDueDate)}.`):`Próximo vencimento em ${dateBr(subscription.nextDueDate)}, respeitando o dia ${subscription.dueDay||'—'} configurado pelo Admin Master.`}</p></div><strong>{overdue&&subscription.daysOverdue>0?`${subscription.daysOverdue} dia(s) em atraso`:dueSoon&&daysToDue!==undefined?(daysToDue===0?'Vence hoje':`${daysToDue} dia(s)`):`Dia ${subscription.dueDay||'—'}`}</strong></section>}

    <section className="admin-card food-current-plan-v046"><div><span>PLANO ATUAL</span><h2>{overview?.currentPlan?.name||planUsage.plan.name}</h2><strong>{currency.format(subscription?.billingAmount??planUsage.plan.monthlyPrice??0)}/mês</strong></div><div className="food-subscription-meta-v046"><span><CalendarDays size={17}/><small>Dia de vencimento</small><strong>{subscription?.dueDay?`Dia ${subscription.dueDay}`:'—'}</strong></span><span><Clock3 size={17}/><small>Próximo vencimento</small><strong>{dateBr(subscription?.nextDueDate)}</strong></span><span><ReceiptText size={17}/><small>Último pagamento</small><strong>{lastPaid?.paidAt?dateBr(lastPaid.paidAt):'—'}</strong></span></div></section>

    <section className="admin-card food-last-payment-v046"><div className="section-heading"><div><span className="eyebrow">ÚLTIMO PAGAMENTO</span><h2>{lastPaid?'Mensalidade confirmada':'Nenhum pagamento confirmado ainda'}</h2></div><ReceiptText/></div>{lastPaid?<div className="food-last-payment-grid-v046"><span><small>Plano</small><strong>{lastPaid.planName||overview?.currentPlan?.name||planUsage.plan.name}</strong></span><span><small>Valor</small><strong>{currency.format(lastPaid.amount)}</strong></span><span><small>Pago em</small><strong>{dateTimeBr(lastPaid.paidAt)}</strong></span><span><small>Vencimento da referência</small><strong>{dateBr(lastPaid.dueDate)}</strong></span><span><small>Próximo vencimento</small><strong>{dateBr(subscription?.nextDueDate)}</strong></span><span><small>Cobrança</small><strong>#{lastPaid.id.slice(0,8)}</strong></span></div>:<p>Quando o Admin Master confirmar a primeira mensalidade, os dados do pagamento aparecerão aqui.</p>}</section>

    {lastRejected&&(!lastPaid||new Date(lastRejected.createdAt).getTime()>new Date(lastPaid.createdAt).getTime())&&<section className="admin-card food-last-rejection-v046"><AlertTriangle size={21}/><div><strong>Última renovação não foi confirmada</strong><p>{lastRejected.rejectionReason||'O Admin Master marcou a cobrança como não renovada.'}</p><small>Analisado em {dateTimeBr(lastRejected.rejectedAt||lastRejected.createdAt)} · referência {dateBr(lastRejected.dueDate)}</small></div></section>}

    {planUsage.subscriptionStatus==='trial'&&<section className="trial-callout"><Sparkles size={24}/><div><strong>Teste grátis do Profissional</strong><span>{planUsage.expiresAt?`Você pode usar todos os recursos até ${new Date(planUsage.expiresAt).toLocaleDateString('pt-BR')}.`:'Analytics e Financeiro estão liberados durante a degustação.'}</span></div></section>}

    <section className="plan-ladder">{sorted.map((plan)=>{const current=plan.id===planUsage.plan.id||plan.code===planUsage.plan.code;const info=planCopy[plan.code]||{headline:plan.name,description:'',bullets:[]};return <article className={`plan-tier ${plan.code==='STARTER'?'highlight':''} ${current?'current':''}`} key={plan.id}>{plan.code==='STARTER'&&<span className="plan-ribbon">Mais indicado</span>}<div className="plan-tier-head"><div><span className="plan-tier-name">{plan.name}</span><h2>{info.headline}</h2><p>{info.description}</p></div><div className="plan-tier-price"><strong>{currency.format(plan.monthlyPrice||0)}</strong><span>/mês</span></div></div><div className="plan-tier-features">{info.bullets.map((item)=><span key={item}><Check size={16}/>{item}</span>)}<span><Images size={16}/>{plan.imageLimitPerProduct===1?'1 foto por produto':`Até ${plan.imageLimitPerProduct??'várias'} fotos por produto`}</span>{planHasFeature(plan,'analytics')&&<span><BarChart3 size={16}/>Analytics habilitado</span>}{planHasFeature(plan,'finance')&&<span><WalletCards size={16}/>Financeiro habilitado</span>}</div><div className="plan-tier-action">{current&&<span className="plan-current-label"><Check size={15}/>Seu plano atual</span>}<button className={current?'secondary-button':'primary-button'} disabled={Boolean(busy)} onClick={()=>void generate(plan)}><QrCode size={17}/>{busy===plan.id?'Gerando PIX...':current?'Renovar com PIX':`Mudar para ${plan.name}`}</button></div></article>})}</section>

    <section className="admin-card food-business-plan-v051"><div className="food-business-plan-head-v051"><div><span className="eyebrow">SOB MEDIDA</span><h2>Business</h2></div><span><Crown size={15}/>Projeto personalizado</span></div><div className="food-business-price-v051"><strong>Sob consulta</strong><small>Valor definido depois do levantamento do escopo</small></div><div className="food-business-features-v051"><span><Globe2 size={17}/>Domínio próprio incluído</span><span><BarChart3 size={17}/>Relatórios e processos sob medida</span><span><Puzzle size={17}/>Integrações com ERP, PDV, financeiro e APIs</span><span><Check size={17}/>Módulos, automações e fluxos personalizados</span><span><ShieldCheck size={17}/>Acompanhamento técnico dedicado</span></div><p>O Business não entra na renovação automática por PIX porque cada projeto possui escopo e valor próprios. A contratação é tratada diretamente com o suporte FoodWeb.</p></section>

    <section className="billing-explainer"><div><WalletCards size={22}/><div><h2>Pagamento simples por PIX</h2><p>O valor é obtido do plano no servidor. Depois do pagamento, o envio do comprovante pelo WhatsApp é obrigatório e o Admin Master confirma a ativação.</p></div></div><span className="automation-pill">Conferência manual</span></section>

    {charge&&<section className="subscription-charge subscription-charge-v4"><div className="subscription-charge-main"><span className="charge-icon"><QrCode/></span><div><span className="charge-intent">{isPlanChange?'ALTERAÇÃO DE PLANO':'RENOVAÇÃO'}</span><h2>{isPlanChange?`${planUsage.plan.name} → ${charge.plan.name}`:`Plano ${charge.plan.name}`}</h2><p>{currency.format(charge.payment.amount)} · referência {dateBr(charge.payment.dueDate)}</p></div></div><div className="subscription-steps"><span className="done">1</span><strong>Copie o PIX e realize o pagamento</strong><span>2</span><strong>Envie o comprovante pelo WhatsApp</strong><span>3</span><strong>Aguarde a confirmação do Master</strong></div>{pixCode?<div className="subscription-pix-data"><label>PIX Copia e Cola — {currency.format(charge.payment.amount)}<div><textarea rows={3} readOnly value={pixCode}/><button type="button" onClick={()=>void copy(pixCode).then(()=>showToast('PIX copiado.','success'))}><Copy size={16}/>Copiar PIX</button></div></label><small>Beneficiário: {charge.billing?.pixHolderName} · {charge.billing?.pixCity}</small></div>:<div className="subscription-pix-warning"><ShieldCheck size={18}/><span>O Admin Master ainda precisa configurar uma chave PIX ou um PIX estático válido para gerar o Copia e Cola.</span></div>}{charge.billing?.proofRequired&&<div className="proof-flow proof-flow-required"><div className="proof-flow-title"><MessageCircleMore size={18}/><div><strong>Comprovante obrigatório</strong><span>Abra o WhatsApp, anexe o comprovante e só depois confirme abaixo.</span></div></div><button className="whatsapp-proof-button" onClick={openProofWhatsApp}><MessageCircleMore size={18}/>Enviar comprovante pelo WhatsApp</button>{!charge.payment.proofSentAt&&<button className="secondary-button" disabled={!proofOpened} onClick={()=>void confirmProofSent()}><Check size={17}/>Já enviei o comprovante</button>}{charge.payment.proofSentAt&&<div className="proof-sent-note"><Check size={16}/>Comprovante informado como enviado. Aguardando conferência do Admin Master.</div>}</div>}</section>}

    <section className="admin-card food-billing-note-v046"><Sparkles/><div><strong>Vencimento preservado</strong><p>O pagamento confirmado recebe a data real da confirmação. O próximo vencimento continua seguindo o dia configurado pelo Admin Master; pagar atrasado não empurra a mensalidade para o dia do pagamento.</p></div></section>

    {overview&&overview.payments.length>0&&<section className="admin-card food-payment-history-v046"><div className="section-heading"><div><span className="eyebrow">HISTÓRICO RECENTE</span><h2>Últimas cobranças</h2></div></div><div>{overview.payments.slice(0,5).map((payment)=><div className="food-payment-history-row-v046" key={payment.id}><span><strong>{payment.paymentIntent==='plan_change'?'Alteração de plano':'Mensalidade'}</strong><small>#{payment.id.slice(0,8)} · referência {dateBr(payment.dueDate)}</small></span><span>{currency.format(payment.amount)}</span><b className={`status-${payment.status}`}>{paymentStatusLabel(payment.status)}</b></div>)}</div></section>}
  </>;
}
