import { BadgeDollarSign, Bot, Check, Clock3, QrCode, Save, ShieldCheck, WalletCards } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { useToast } from '../../contexts/ToastContext';
import { platformApi } from '../../services/platformApi';
import type { Plan, PlatformSettings } from '../../types';
import { currency } from '../../utils/format';
import { planHasFeature } from '../../utils/plan';

const defaultSettings:PlatformSettings={demoEnabled:true,demoDurationDays:14,demoWarningDays:3,billingProvider:'manual',billingPixKeyType:'',billingPixKey:'',billingPixHolderName:'',billingPixCopyPaste:'',billingWhatsapp:'',billingProofRequired:true,billingAutoRenew:false,billingGraceDays:3};

export default function MasterPlans(){
  const{showToast}=useToast();const[plans,setPlans]=useState<Plan[]>([]);const[settings,setSettings]=useState<PlatformSettings>(defaultSettings);const[saving,setSaving]=useState('');const[savingSettings,setSavingSettings]=useState(false);
  useEffect(()=>{void Promise.all([platformApi.listPlans(),platformApi.getPlatformSettings()]).then(([p,s])=>{setPlans(p);setSettings(s)}).catch((e)=>showToast(e instanceof Error?e.message:'Falha ao carregar planos.','error'))},[]);
  const paid=useMemo(()=>plans.filter((p)=>p.code!=='DEMO'&&p.active).sort((a,b)=>(a.sortOrder||0)-(b.sortOrder||0)),[plans]);
  const update=(id:string,patch:Partial<Plan>)=>setPlans((items)=>items.map((p)=>p.id===id?{...p,...patch}:p));
  const savePlan=async(plan:Plan)=>{setSaving(plan.id);try{const saved=await platformApi.savePlan(plan);update(plan.id,saved);showToast(`Plano ${saved.name} atualizado.`,'success')}catch(e){showToast(e instanceof Error?e.message:'Erro ao salvar plano.','error')}finally{setSaving('')}};
  const saveSettings=async()=>{if(settings.demoWarningDays>=settings.demoDurationDays){showToast('O aviso deve ser menor que o período do teste.','error');return}if(settings.billingProvider==='manual'&&!settings.billingPixKey.trim()&&!settings.billingPixCopyPaste.trim()){showToast('Informe a chave PIX ou o copia e cola da plataforma para cobrança manual.','error');return}if(settings.billingProvider==='manual'&&settings.billingProofRequired&&!settings.billingWhatsapp.replace(/\D/g,'').trim()){showToast('Informe o WhatsApp que receberá os comprovantes da cobrança manual.','error');return}setSavingSettings(true);try{const saved=await platformApi.savePlatformSettings(settings);setSettings(saved);showToast('Configurações comerciais salvas.','success')}catch(e){showToast(e instanceof Error?e.message:'Falha ao salvar configurações.','error')}finally{setSavingSettings(false)}};
  return <>
    <div className="admin-page-title"><div><h1>Planos e cobrança</h1><p>Três planos pagos, teste grátis do Profissional e a forma como a plataforma recebe suas mensalidades.</p></div><a className="secondary-button" href="/admin-master/pagamentos"><WalletCards size={17}/>Ver pagamentos</a></div>

    <section className="master-commercial-config">
      <div className="trial-config-panel"><div className="section-heading"><div><h2>Teste grátis do Profissional</h2><p>O lojista experimenta Analytics e Financeiro antes de escolher um plano.</p></div><Clock3/></div><label className="switch-row"><span><strong>Oferecer teste grátis</strong><small>Novas lojas podem receber a degustação completa.</small></span><input type="checkbox" checked={settings.demoEnabled} onChange={(e)=>setSettings((s)=>({...s,demoEnabled:e.target.checked}))}/></label><div className="two-col-form"><label>Duração (dias)<input type="number" min="7" max="30" value={settings.demoDurationDays} onChange={(e)=>setSettings((s)=>({...s,demoDurationDays:Number(e.target.value)}))}/></label><label>Avisar com antecedência<input type="number" min="1" max="14" value={settings.demoWarningDays} onChange={(e)=>setSettings((s)=>({...s,demoWarningDays:Number(e.target.value)}))}/></label></div><div className="master-config-note"><Check size={16}/><span>Recomendação atual: 14 dias. O teste usa as mesmas funcionalidades do Profissional.</span></div></div>

      <div className="billing-config-panel"><div className="section-heading"><div><h2>Cobrança da assinatura</h2><p>Comece no PIX manual e ative automação quando tiver o Asaas configurado.</p></div><QrCode/></div><div className="billing-provider-toggle"><button type="button" className={settings.billingProvider==='manual'?'active':''} onClick={()=>setSettings((s)=>({...s,billingProvider:'manual',billingAutoRenew:false}))}><WalletCards/>PIX manual<small>Sem integração externa</small></button><button type="button" className={settings.billingProvider==='asaas'?'active':''} onClick={()=>setSettings((s)=>({...s,billingProvider:'asaas',billingAutoRenew:true}))}><Bot/>Asaas<small>PIX dinâmico + webhook</small></button></div>{settings.billingProvider==='manual'?<div className="billing-config-fields"><label>Tipo da chave<input value={settings.billingPixKeyType} onChange={(e)=>setSettings((s)=>({...s,billingPixKeyType:e.target.value}))} placeholder="CNPJ, telefone, e-mail..."/></label><label>Chave PIX<input value={settings.billingPixKey} onChange={(e)=>setSettings((s)=>({...s,billingPixKey:e.target.value}))}/></label><label>Titular<input value={settings.billingPixHolderName} onChange={(e)=>setSettings((s)=>({...s,billingPixHolderName:e.target.value}))}/></label><label>WhatsApp para comprovantes<input value={settings.billingWhatsapp} onChange={(e)=>setSettings((s)=>({...s,billingWhatsapp:e.target.value}))} placeholder="5527999999999"/></label><label className="full">PIX copia e cola opcional<textarea rows={3} value={settings.billingPixCopyPaste} onChange={(e)=>setSettings((s)=>({...s,billingPixCopyPaste:e.target.value}))}/></label><label className="switch-row full"><span><strong>Exigir envio do comprovante</strong><small>O Master só consegue confirmar cobrança manual depois do registro do envio.</small></span><input type="checkbox" checked={settings.billingProofRequired} onChange={(e)=>setSettings((s)=>({...s,billingProofRequired:e.target.checked}))}/></label></div>:<div className="asaas-config-note"><ShieldCheck/><div><strong>Chaves ficam fora do banco</strong><p>Configure <code>ASAAS_API_KEY</code>, <code>ASAAS_ENVIRONMENT</code> e <code>ASAAS_WEBHOOK_TOKEN</code> nos Secrets das Edge Functions. A API key nunca vai para o frontend.</p><div className="master-config-note"><Check size={16}/><span>Com Asaas ativo, o webhook renova a assinatura automaticamente quando o recebimento PIX chegar como PAYMENT_RECEIVED.</span></div></div></div>}<div className="two-col-form billing-grace-row"><label>Carência após vencimento (dias)<input type="number" min="0" max="30" value={settings.billingGraceDays} onChange={(e)=>setSettings((s)=>({...s,billingGraceDays:Number(e.target.value)}))}/><small>Depois deste prazo, a loja é suspensa automaticamente até a renovação.</small></label></div></div>
    </section>

    <div className="master-plan-ladder">{paid.map((plan)=>{const currentFeature=planHasFeature(plan,'finance')?'Gestão completa':planHasFeature(plan,'analytics')?'Inteligência de vendas':'Cardápio + WhatsApp';return <article className={`admin-card master-plan-card-v3 ${plan.code==='STARTER'?'featured':''}`} key={plan.id}>{plan.code==='STARTER'&&<span className="plan-featured-badge">Meio da escada</span>}<div className="master-plan-title-v3"><div><span>{plan.code}</span><input value={plan.name} onChange={(e)=>update(plan.id,{name:e.target.value})}/><small>{currentFeature}</small></div><label><input type="checkbox" checked={plan.active} onChange={(e)=>update(plan.id,{active:e.target.checked})}/>Ativo</label></div><div className="master-plan-price-v3"><BadgeDollarSign/><label><span>Mensalidade</span><input type="number" step="0.01" min="0" value={plan.monthlyPrice||0} onChange={(e)=>update(plan.id,{monthlyPrice:Number(e.target.value)})}/><small>{currency.format(plan.monthlyPrice||0)}/mês</small></label></div><div className="master-plan-limits-v3"><label>Produtos<input type="number" min="0" value={plan.productLimit??''} placeholder="Ilimitado" onChange={(e)=>update(plan.id,{productLimit:e.target.value===''?null:Number(e.target.value)})}/></label><label>Fotos / produto<input type="number" min="1" value={plan.imageLimitPerProduct??''} onChange={(e)=>update(plan.id,{imageLimitPerProduct:e.target.value===''?null:Number(e.target.value)})}/></label><label>Usuários admin<input type="number" min="1" value={plan.adminUserLimit??''} onChange={(e)=>update(plan.id,{adminUserLimit:e.target.value===''?null:Number(e.target.value)})}/></label></div><div className="plan-feature-chips"><span><Check/>Pedidos</span><span><Check/>WhatsApp</span>{planHasFeature(plan,'analytics')&&<span><Check/>Analytics</span>}{planHasFeature(plan,'finance')&&<span><Check/>Financeiro</span>}{planHasFeature(plan,'custom_banner')&&<span><Check/>Banners</span>}</div><button className="primary-button full-button" disabled={saving===plan.id} onClick={()=>void savePlan(plan)}><Save size={17}/>{saving===plan.id?'Salvando...':'Salvar plano'}</button></article>})}</div>
    <button className="primary-button master-save-commercial" disabled={savingSettings} onClick={()=>void saveSettings()}><Save size={17}/>{savingSettings?'Salvando...':'Salvar teste e cobrança'}</button>
  </>;
}
