import fs from 'node:fs';
import path from 'node:path';

const root=process.cwd();
const read=(file)=>fs.readFileSync(path.join(root,file),'utf8');
const checks=[];const failures=[];
const check=(name,condition)=>{checks.push([name,condition]);if(!condition)failures.push(name)};

const checkout=read('src/pages/store/Checkout.tsx');
const product=read('src/pages/store/ProductDetail.tsx');
const cart=read('src/contexts/CartContext.tsx');
const storeApi=read('src/services/storeApi.ts');
const platformApi=read('src/services/platformApi.ts');
const success=read('src/pages/store/OrderSuccess.tsx');
const orders=read('src/pages/admin/Orders.tsx');
const edge=read('supabase/functions/food-public-checkout/index.ts');
const migration=read('supabase/migrations/202608280400_foodservice_shared_database.sql');
const commercial=read('supabase/migrations/202608310900_foodservice_commercial_finance_v030.sql');
const v040=read('supabase/migrations/202609020800_foodweb_v040_manual_pix_finance_visual.sql');
const config=read('supabase/config.toml');
const localReader=read('src/utils/localFinancialDocumentReader.ts');
const financePage=read('src/pages/admin/Finance.tsx');
const planPage=read('src/pages/admin/Plan.tsx');
const masterPlans=read('src/pages/master/Plans.tsx');
const v043=read('supabase/migrations/202609021600_foodweb_v043_storefront_sales_whatsapp.sql');
const v044=read('supabase/migrations/202609031500_foodweb_v044_security_contact.sql');
const landing=read('src/pages/store/Landing.tsx');
const publicContact=read('supabase/functions/food-public-contact/index.ts');
const adminLogin=read('src/pages/admin/Login.tsx');
const masterLogin=read('src/pages/master/Login.tsx');
const auth=read('src/contexts/AuthContext.tsx');
const home=read('src/pages/store/Home.tsx');
const adminLayout=read('src/layouts/AdminLayout.tsx');

const registered=checkout.indexOf('await registerOrder(');
const whatsappMessage=checkout.indexOf('buildWhatsAppMessage(');
const confirmation=checkout.indexOf('saveOrderConfirmation(confirmation)');
const clearCart=checkout.indexOf('clear();');
const navigate=checkout.indexOf('navigate(storefrontPath');

check('Pedido é registrado antes de montar WhatsApp',registered>=0&&whatsappMessage>registered);
check('Confirmação local ocorre depois do banco',confirmation>registered);
check('Carrinho só é limpo depois da confirmação',clearCart>confirmation);
check('Navegação ocorre após limpar carrinho',navigate>clearCart);
check('Checkout usa requestId idempotente',checkout.includes('requestId')&&storeApi.includes('requestId:security.requestId'));
check('Unique key Food de idempotência existe',migration.includes('unique(store_id,public_request_id)'));
check('Edge injeta requestId no payload do banco',edge.includes('public_request_id: requestId'));
check('Edge recupera replay em food_orders',edge.includes('idempotentReplay')&&edge.includes("from('food_orders')"));
check('RPC Food só é executável pelo service_role',migration.includes('grant execute on function public.food_create_public_order(jsonb) to service_role'));
check('Checkout público continua sem JWT',config.includes('[functions.food-public-checkout]')&&config.includes('verify_jwt = false'));
check('Turnstile é validado no servidor',edge.includes('validateTurnstile(token, remoteIp, origin)'));
check('Origem oficial é permitida por padrão',edge.includes("'https://foodweb.joseluizacama.workers.dev'"));
check('POST continua bloqueando origem indevida',edge.includes('originIsAllowed')&&edge.includes('ORIGIN_NOT_ALLOWED'));
check('Banco recalcula preço',migration.includes('coalesce(v_product.promotional_price,v_product.price)'));
check('Banco valida opção no produto/loja',migration.includes('pog.product_id=v_product.id')&&migration.includes('pog.store_id=v_store.id'));
check('Banco valida mínimo/máximo',migration.includes('v_choice_count<v_group.min_choices')&&migration.includes('v_choice_count>v_group.max_choices'));
check('Banco recalcula taxa',migration.includes('v_delivery_fee := v_zone.fee'));
check('Banco rejeita loja fechada',migration.includes('food_store_is_accepting_orders(v_store.id,now())'));
check('Banco valida agendamento',migration.includes('food_store_is_accepting_orders(v_store.id,v_scheduled_for)'));
check('Frontend valida grupos obrigatórios',product.includes('group.minChoices')&&product.includes('group.maxChoices'));
check('Carrinho usa assinatura das personalizações',cart.includes('normalizedOptionKey'));
check('WhatsApp só abre após pedido existente',success.includes('markOrderWhatsAppClicked(confirmation.orderId)'));
check('Status operacional não depende do WhatsApp',orders.includes('Em preparação')&&orders.includes('Pronto')&&orders.includes('Saiu para entrega'));
check('Food Master lê apenas food_*',platformApi.includes('food_stores?')&&platformApi.includes('food_plans?')&&!platformApi.includes("'stores?"));
check('Food Admin lê apenas food_*',storeApi.includes('food_products?')&&storeApi.includes('food_orders?')&&!storeApi.includes('`products?'));

check('Plano financeiro é protegido pelo banco',commercial.includes("food_store_has_feature(p_store_id,'finance')"));
check('Pagamento manual exige comprovante antes da confirmação',commercial.includes("v_payment.provider='manual' and v_payment.proof_required and v_payment.proof_sent_at is null"));
check('Confirmação de mensalidade é idempotente',commercial.includes("if v_payment.status='paid' then return v_payment"));
check('Confirmação renova e reativa loja',commercial.includes("interval '1 month'")&&commercial.includes("access_status='online'"));
check('v0.4 força cobrança manual',v040.includes("billing_provider='manual'")&&v040.includes('billing_auto_renew=false'));
check('Preço cobrado vem do plano no banco',v040.includes('v_plan.monthly_price')&&planPage.includes('charge.payment.amount'));
check('Alteração de plano é auditável',v040.includes('previous_plan_id')&&v040.includes("v_intent := 'plan_change'"));
check('Só uma decisão de plano pendente permanece',v040.includes("status='cancelled'")&&v040.includes("plan_id<>p_plan_id"));
check('WhatsApp é obrigatório para comprovante',v040.includes('billing_whatsapp')&&masterPlans.includes('WhatsApp para comprovantes'));
check('OCR não grava direção automaticamente no formulário',!financePage.includes('direction:suggestion.direction'));
check('Boleto reconhece valor e vencimento localmente',localReader.includes('amountFromBoletoDigits')&&localReader.includes('extractDueOn')&&localReader.includes('boletoDigits'));
check('OCR local não grava financeiro automaticamente',!localReader.includes('financial_entries')&&financePage.includes('financeApi.saveEntry'));
check('Leitura financeira não depende de upload para Storage',!financePage.includes('uploadDocument')&&!financePage.includes('linkDocument'));
check('Leitura local valida MIME e tamanho',localReader.includes('MAX_IMAGE_BYTES')&&localReader.includes('MAX_PDF_BYTES')&&localReader.includes('ensureAllowedFile'));
check('Financeiro de pedido evita duplicidade',commercial.includes('food_financial_entries_order_uidx')&&commercial.includes('on conflict(store_id,order_id)'));
check('Plano Essencial não burla limite de foto',commercial.includes('food_enforce_product_image_plan_limit'));
check('Plano sem banner não burla capa personalizada',commercial.includes('food_enforce_custom_banner_plan'));
check('Downgrade respeita recursos públicos',commercial.includes('v_custom_banner:=public.food_store_has_feature')&&commercial.includes('v_image_limit:=public.food_current_plan_image_limit'));
check('Acesso pago vence depois da carência',commercial.includes('food_suspend_overdue_paid_subscriptions'));
check('Agendamento Demo é verificado no pg_cron',v040.includes("jobname='foodservice-demo-expiration-hourly'")&&v040.includes('bool_or(active)'));
check('Renovação antecipada preserva período pago',commercial.includes('greatest(coalesce(v_sub.next_due_date'));
check('Landing publica nao expoe dados privados da loja', !read('supabase/migrations/202609021020_foodweb_v042_public_landing.sql').includes('owner_email'));
check('Landing publica so lista lojas acessiveis', v043.includes('food_store_accessible(s.id)'));
check('v0.4.3 preserva namespace Food',!/alter table public\.(stores|products|orders|plans|platform_settings)\b/i.test(v043));
const v044PublicLanding=v044.slice(0,v044.indexOf('food_get_admin_support_contact_v1'));
check('v0.4.4 remove telefones da landing pública',v044PublicLanding.includes('food_get_public_landing_v1')&&!v044PublicLanding.includes("'marketing_whatsapp',")&&!v044PublicLanding.includes("'support_whatsapp',"));
check('Contato comercial exige Turnstile e origem',publicContact.includes('validateTurnstile')&&publicContact.includes('originAllowed')&&publicContact.includes("result.action&&result.action!=='marketing'"));
check('Contato comercial possui rate limit sem IP bruto',publicContact.includes('food_enforce_public_contact_rate_limit')&&publicContact.includes('sha256')&&v044.includes('food_public_contact_rate_limits'));
check('Suporte da plataforma é somente autenticado',v044.includes('food_get_admin_support_contact_v1')&&v044.includes("su.role in ('owner','admin')")&&!home.includes('PlatformHelpButton')&&adminLayout.includes('PlatformHelpButton'));
check('Logins enviam captchaToken ao Supabase Auth',adminLogin.includes('action="login"')&&masterLogin.includes('action="login"')&&auth.includes('options: captchaToken ? { captchaToken }'));
check('Landing usa contato protegido sem wa.me público',landing.includes('ProtectedContactButton')&&!landing.includes('wa.me/')&&!landing.includes('marketingWhatsapp'));
check('v0.4.4 preserva namespace Food',!/alter table public\.(stores|products|orders|plans|platform_settings)\b/i.test(v044));

for(const[name,condition]of checks)console.log(`${condition?'OK  ':'FAIL'} ${name}`);
if(failures.length){
  console.error(`\n${failures.length} falha(s) críticas:`);
  for(const failure of failures)console.error(`- ${failure}`);
  process.exit(1);
}
console.log(`\nFluxo crítico FoodWeb v0.4 concluído: ${checks.length} verificações.`);
