import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');
const exists=(p)=>fs.existsSync(path.join(root,p));
const failures=[];
const ok=(name,condition)=>{console.log(`${condition?'OK  ':'ERRO'} ${name}`);if(!condition)failures.push(name)};
const pkg=JSON.parse(read('package.json'));
const types=read('src/types/index.ts');
const settings=read('src/pages/admin/Settings.tsx');
const finance=read('src/pages/admin/Finance.tsx');
const orders=read('src/pages/admin/Orders.tsx');
const header=read('src/components/StoreHeader.tsx');
const success=read('src/pages/store/OrderSuccess.tsx');
const master=read('src/layouts/MasterLayout.tsx');
const styles=read('src/styles.css');
const storeHours=read('src/utils/storeHours.ts');
const adminLayout=read('src/layouts/AdminLayout.tsx');
const helpButton=read('src/components/PlatformHelpButton.tsx');
const home=read('src/pages/store/Home.tsx');
ok('Versao 0.5.2',pkg.version==='0.5.2');
ok('Pausa de almoco no tipo',types.includes('breakStart?: string')&&types.includes('breakEnd?: string'));
ok('Recebimento preservado no pedido',types.includes("OrderPaymentStatus = 'pending' | 'paid'")&&types.includes('paymentStatus: OrderPaymentStatus')&&types.includes('paymentReceivedAt?: string'));
ok('Pedidos preservam confirmacao de recebimento',orders.includes('Confirmar recebimento')&&orders.includes('confirmOrderPayment'));
ok('Pedidos preservam atualizacao automatica',orders.includes('setInterval')&&orders.includes('visibilitychange')&&/reloadAdmin\(\{\s*silent\s*:\s*true\s*\}\)/.test(orders));
ok('Configuracao de almoco no admin',settings.includes('Fechar para almoço')&&settings.includes('breakStart')&&settings.includes('breakEnd'));
ok('Pedidos Food com filtro e ordenacao',orders.includes('orders-toolbar--filters')&&orders.includes('Ordenar por')&&orders.includes('statusFilter'));
ok('Pedido relacionado usa highlight',finance.includes('/admin/pedidos?highlight=')&&orders.includes('order-row-highlighted'));
ok('Horario Food mostra hoje e semana',header.includes('<strong>Hoje</strong>')&&header.includes('Ver horários da semana')&&header.includes('food-hours-popover'));
ok('Popover fecha fora e com ESC',header.includes("document.addEventListener('pointerdown'")&&header.includes("event.key==='Escape'")&&header.includes('hoursRef'));
ok('PIX copia e cola tem acao visivel',success.includes('aria-label="Copiar PIX"')&&success.includes('title="Copiar PIX"'));
ok('Admin Master preservado',master.includes('master-admin-mini')&&master.includes('FoodWeb'));
ok('Identidade Food preservada no admin',styles.includes('--admin-accent: #d4572b')||styles.includes('--food-red'));
ok('Favicon v0.5.2 existe',exists('public/favicon-foodweb-v052.svg')&&read('index.html').includes('favicon-foodweb-v052.svg'));
ok('Horario atravessa meia-noite preservado',storeHours.includes('previousDayNumber')&&storeHours.includes('previousDay'));
ok('Suporte flutuante restrito ao Admin',helpButton.includes('loadAdminSupportContact')&&/<PlatformHelpButton\s*\/>/.test(adminLayout)&&/<PlatformHelpButton\s*\/>/.test(master)&&!home.includes('PlatformHelpButton'));
if(failures.length){console.error(`\nv0.5.2 com ${failures.length} falha(s).`);process.exit(1)}
console.log('\nFoodWeb v0.5.2 pronto para validacao e publicacao.');
