import { ArrowDownRight, ArrowUpRight, FileSearch2, Loader2, Plus, ReceiptText, Save, Sparkles, Upload } from 'lucide-react';
import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { useStore } from '../../contexts/StoreContext';
import { useToast } from '../../contexts/ToastContext';
import { financeApi } from '../../services/financeApi';
import type { FinancialCategory, FinancialDirection, FinancialDocument, FinancialDocumentType, FinancialEntry, FinancialEntryStatus } from '../../types';
import { currency } from '../../utils/format';
import { planHasFeature } from '../../utils/plan';

const today=()=>new Date().toISOString().slice(0,10);
const documentTypes:{value:FinancialDocumentType;label:string}[]=[{value:'none',label:'Sem documento'},{value:'coupon',label:'Cupom fiscal'},{value:'nfe',label:'NF-e'},{value:'nfce',label:'NFC-e'},{value:'nfse',label:'NFS-e'},{value:'boleto',label:'Boleto'},{value:'receipt',label:'Recibo'},{value:'other',label:'Outro'}];
const emptyForm=(storeId:string)=>({storeId,direction:'expense' as FinancialDirection,categoryId:'',description:'',amount:0,occurredOn:today(),dueOn:'',status:'paid' as FinancialEntryStatus,paymentMethod:'',counterparty:'',documentType:'none' as FinancialDocumentType,documentNumber:'',notes:''});

export default function Finance(){
  const {settings,planUsage}=useStore();const {showToast}=useToast();const enabled=planHasFeature(planUsage.plan,'finance');
  const[categories,setCategories]=useState<FinancialCategory[]>([]);const[entries,setEntries]=useState<FinancialEntry[]>([]);const[form,setForm]=useState(()=>emptyForm(settings.id));const[attachedDocument,setAttachedDocument]=useState<FinancialDocument|null>(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[extracting,setExtracting]=useState(false);
  const reload=async()=>{setLoading(true);try{const[c,e]=await Promise.all([financeApi.listCategories(settings.id),financeApi.listEntries(settings.id)]);setCategories(c);setEntries(e);}catch(err){showToast(err instanceof Error?err.message:'Falha ao carregar o financeiro.','error')}finally{setLoading(false)}};
  useEffect(()=>{setForm(emptyForm(settings.id));if(enabled)void reload();else setLoading(false);},[settings.id,enabled]);
  const summary=useMemo(()=>{const valid=entries.filter((entry)=>entry.status==='paid');const income=valid.filter((entry)=>entry.direction==='income').reduce((sum,e)=>sum+e.amount,0);const expense=valid.filter((entry)=>entry.direction==='expense').reduce((sum,e)=>sum+e.amount,0);const pending=entries.filter((entry)=>entry.status==='pending').reduce((sum,e)=>sum+e.amount,0);return{income,expense,result:income-expense,pending}},[entries]);
  const categoryOptions=categories.filter((category)=>category.direction==='both'||category.direction===form.direction);
  const upload=async(file?:File)=>{if(!file)return;try{setExtracting(true);const doc=await financeApi.uploadDocument(settings.id,file);setAttachedDocument(doc);const result=await financeApi.extractDocument(settings.id,doc);const s=result.suggestion;const category=s.categoryName?categories.find((c)=>c.name.toLowerCase()===String(s.categoryName).toLowerCase()):undefined;setForm((current)=>({...current,direction:s.direction||current.direction,amount:s.amount??current.amount,occurredOn:s.occurredOn||current.occurredOn,documentType:s.documentType||current.documentType,documentNumber:s.documentNumber||'',counterparty:s.counterparty||'',description:s.description||current.description,categoryId:category?.id||current.categoryId}));showToast(`Documento interpretado${s.confidence!=null?` · confiança ${Math.round(s.confidence*100)}%`:''}. Revise antes de salvar.`,'success');}catch(err){showToast(err instanceof Error?err.message:'Não foi possível interpretar o documento. Preencha manualmente.','error')}finally{setExtracting(false)}};
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!form.description.trim()||form.amount<=0){showToast('Informe descrição e valor maior que zero.','error');return}setSaving(true);try{const saved=await financeApi.saveEntry({...form,dueOn:form.dueOn||undefined,categoryId:form.categoryId||undefined,paidAt:form.status==='paid'?new Date().toISOString():undefined});if(attachedDocument)await financeApi.linkDocument(attachedDocument.id,saved.id);showToast('Lançamento financeiro salvo.','success');setForm(emptyForm(settings.id));setAttachedDocument(null);await reload();}catch(err){showToast(err instanceof Error?err.message:'Falha ao salvar lançamento.','error')}finally{setSaving(false)}};
  if(!enabled)return <section className="feature-lock"><div><ReceiptText size={28}/><h1>Financeiro disponível no Profissional</h1><p>Fluxo de caixa gerencial, entradas, saídas e leitura assistida de documentos ficam preservados como um módulo premium.</p><a className="primary-button" href="/admin/plano">Conhecer o Profissional</a></div></section>;
  return <>
    <div className="admin-page-title finance-heading"><div><h1>Financeiro</h1><p>Visão gerencial simples para entender o que entrou, o que saiu e o resultado da operação.</p></div><button className="primary-button" onClick={()=>document.getElementById('finance-entry-form')?.scrollIntoView({behavior:'smooth'})}><Plus size={17}/>Novo lançamento</button></div>
    <section className="finance-summary-band"><div><span>Entradas realizadas</span><strong>{currency.format(summary.income)}</strong><small><ArrowUpRight size={14}/>Pedidos concluídos entram automaticamente</small></div><div><span>Saídas realizadas</span><strong>{currency.format(summary.expense)}</strong><small><ArrowDownRight size={14}/>Despesas registradas</small></div><div className={summary.result>=0?'positive':'negative'}><span>Resultado gerencial</span><strong>{currency.format(summary.result)}</strong><small>Receitas − despesas pagas</small></div><div><span>Pendentes</span><strong>{currency.format(summary.pending)}</strong><small>Valores ainda não liquidados</small></div></section>

    <section className="finance-workspace" id="finance-entry-form">
      <form className="finance-entry-form" onSubmit={submit}><div className="section-heading"><div><h2>Novo lançamento</h2><p>Cadastre manualmente ou envie um documento para preencher os campos.</p></div></div>
        <div className="finance-direction-toggle"><button type="button" className={form.direction==='income'?'active':''} onClick={()=>setForm((f)=>({...f,direction:'income',categoryId:''}))}><ArrowUpRight/>Entrada</button><button type="button" className={form.direction==='expense'?'active':''} onClick={()=>setForm((f)=>({...f,direction:'expense',categoryId:''}))}><ArrowDownRight/>Saída</button></div>
        <label className="finance-document-drop"><input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={(e)=>void upload(e.target.files?.[0])}/>{extracting?<Loader2 className="spin"/>:<Upload/>}<span><strong>{extracting?'Lendo documento...':'Foto, cupom, nota, boleto ou PDF'}</strong><small>A IA sugere os dados; você confirma antes de gravar.</small></span></label>
        {attachedDocument&&<div className="finance-ai-note"><Sparkles size={16}/><span>{attachedDocument.originalName} carregado. Revise os campos abaixo.</span></div>}
        <div className="finance-form-grid"><label>Descrição<input value={form.description} onChange={(e)=>setForm((f)=>({...f,description:e.target.value}))} placeholder="Ex.: Compra de ingredientes" required/></label><label>Valor (R$)<input type="number" min="0.01" step="0.01" value={form.amount||''} onChange={(e)=>setForm((f)=>({...f,amount:Number(e.target.value)}))} required/></label><label>Categoria<select value={form.categoryId} onChange={(e)=>setForm((f)=>({...f,categoryId:e.target.value}))}><option value="">Sem categoria</option>{categoryOptions.map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Data<input type="date" value={form.occurredOn} onChange={(e)=>setForm((f)=>({...f,occurredOn:e.target.value}))}/></label><label>Situação<select value={form.status} onChange={(e)=>setForm((f)=>({...f,status:e.target.value as FinancialEntryStatus}))}><option value="paid">Pago/recebido</option><option value="pending">Pendente</option></select></label><label>Fornecedor / origem<input value={form.counterparty} onChange={(e)=>setForm((f)=>({...f,counterparty:e.target.value}))}/></label><label>Tipo de documento<select value={form.documentType} onChange={(e)=>setForm((f)=>({...f,documentType:e.target.value as FinancialDocumentType}))}>{documentTypes.map((d)=><option key={d.value} value={d.value}>{d.label}</option>)}</select></label><label>Número do documento<input value={form.documentNumber} onChange={(e)=>setForm((f)=>({...f,documentNumber:e.target.value}))}/></label></div>
        <label>Observação<textarea rows={3} value={form.notes} onChange={(e)=>setForm((f)=>({...f,notes:e.target.value}))}/></label><button className="primary-button" disabled={saving} type="submit"><Save size={17}/>{saving?'Salvando...':'Salvar lançamento'}</button>
      </form>

      <div className="finance-ledger"><div className="section-heading"><div><h2>Movimentações</h2><p>Histórico mais recente da loja.</p></div><FileSearch2 size={21}/></div>{loading?<p>Carregando...</p>:entries.length===0?<div className="empty-ledger"><ReceiptText/><strong>Nenhum lançamento ainda</strong><span>Conclua um pedido ou registre sua primeira movimentação.</span></div>:<div className="finance-ledger-list">{entries.slice(0,40).map((entry)=><article key={entry.id}><span className={`finance-entry-icon ${entry.direction}`} >{entry.direction==='income'?<ArrowUpRight/>:<ArrowDownRight/>}</span><div><strong>{entry.description}</strong><small>{new Date(`${entry.occurredOn}T12:00:00`).toLocaleDateString('pt-BR')} · {categories.find((c)=>c.id===entry.categoryId)?.name||'Sem categoria'}{entry.source==='order'?' · pedido':''}</small></div><div className="finance-entry-value"><strong>{entry.direction==='income'?'+':'−'} {currency.format(entry.amount)}</strong><span className={`status-dot ${entry.status}`}>{entry.status==='paid'?'Realizado':entry.status==='pending'?'Pendente':'Cancelado'}</span></div></article>)}</div>}</div>
    </section>
  </>;
}
