import { BarChart3, Check, Copy, Crown, FileText, Images, MessageCircleMore, QrCode, Sparkles, WalletCards } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { ErrorState, LoadingState } from '../../components/ui/AsyncState';
import { useStore } from '../../contexts/StoreContext';
import { useToast } from '../../contexts/ToastContext';
import { billingApi, type StoreBillingSettings } from '../../services/billingApi';
import { platformApi } from '../../services/platformApi';
import type { Plan, SubscriptionCharge } from '../../types';
import { currency } from '../../utils/format';
import { planHasFeature } from '../../utils/plan';

const copy=async(value:string)=>{if(value)await navigator.clipboard.writeText(value)};
const planCopy:Record<string,{headline:string;description:string;bullets:string[]}>= {
  ESSENTIAL:{headline:'Seu cardápio profissional, sem complicação',description:'Para sair do PDF e começar a receber pedidos organizados pelo WhatsApp.',bullets:['Cardápio online + checkout','Pedidos gravados antes do WhatsApp','Delivery e retirada','1 foto por produto']},
  STARTER:{headline:'Entenda o que realmente vende',description:'Tudo do Essencial com inteligência para decidir produto, horário e campanha.',bullets:['Tudo do Essencial','Analytics e conversão','Produtos mais vistos e vendidos','Banners personalizados']},
  PROFESSIONAL:{headline:'Venda e enxergue o resultado do negócio',description:'Para quem quer unir pedidos, análise e controle financeiro gerencial.',bullets:['Tudo do Starter','Financeiro de entradas e saídas','Receitas automáticas dos pedidos','Leitura assistida de nota, cupom e boleto']},
};

export default function AdminPlan(){
  const{settings,planUsage}=useStore();const{showToast}=useToast();const[plans,setPlans]=useState<Plan[]>([]);const[billing,setBilling]=useState<StoreBillingSettings|null>(null);const[charge,setCharge]=useState<SubscriptionCharge|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[busy,setBusy]=useState('');const[proofOpened,setProofOpened]=useState(false);
  useEffect(()=>{let active=true;Promise.all([platformApi.listPlans(),billingApi.getSettings(settings.id)]).then(([rows,b])=>{if(active){setPlans(rows.filter((p)=>p.active&&p.code!=='DEMO'));setBilling(b)}}).catch((e)=>{if(active)setError(e instanceof Error?e.message:'Não foi possível carregar plano e cobrança.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[settings.id]);
  const sorted=useMemo(()=>[...plans].sort((a,b)=>(a.sortOrder||0)-(b.sortOrder||0)),[plans]);
  const generate=async(plan:Plan)=>{setBusy(plan.id);setCharge(null);setProofOpened(false);try{const result=billing?.provider==='asaas'?await billingApi.createAutomaticPix(settings.id,plan.id):await billingApi.createManualCharge(settings.id,plan.id);setCharge(result);showToast('Cobrança PIX gerada.','success')}catch(e){showToast(e instanceof Error?e.message:'Não foi possível gerar a cobrança.','error')}finally{setBusy('')}};
  const openProofWhatsApp=()=>{if(!charge?.billing)return;const phone=(charge.billing.whatsapp||'').replace(/\D/g,'');if(!phone){showToast('O WhatsApp de cobrança ainda não foi configurado pelo Admin Master.','error');return}const text=encodeURIComponent(`Olá! Vou enviar o comprovante da mensalidade FoodWeb.\nLoja: ${settings.name}\nPlano: ${charge.plan.name}\nValor: ${currency.format(charge.payment.amount)}\nCobrança: ${charge.payment.id}\n\nVou anexar o comprovante nesta conversa.`);window.open(`https://wa.me/${phone}?text=${text}`,'_blank','noopener,noreferrer');setProofOpened(true)};
  const confirmProofSent=async()=>{if(!charge)return;try{const payment=await billingApi.markProofSent(charge.payment.id);setCharge({...charge,payment});showToast('Envio do comprovante registrado. Aguardando conferência do pagamento.','success')}catch(e){showToast(e instanceof Error?e.message:'Não foi possível registrar o envio do comprovante.','error')}};
  if(loading)return <LoadingState label="Carregando planos..."/>;if(error)return <ErrorState message={error}/>;
  return <>
    <div className="admin-page-title subscription-heading"><div><h1>Plano e assinatura</h1><p>Comece com 14 dias do Profissional e escolha o nível que acompanha o momento da sua operação.</p></div><div className="current-plan-pill"><Crown size={17}/><span>Plano atual</span><strong>{planUsage.plan.name}</strong></div></div>
    {planUsage.subscriptionStatus==='trial'&&<section className="trial-callout"><Sparkles size={24}/><div><strong>Você está degustando o Profissional</strong><span>{planUsage.expiresAt?`Teste grátis até ${new Date(planUsage.expiresAt).toLocaleDateString('pt-BR')}.`: 'Durante o teste, Analytics e Financeiro ficam liberados para você experimentar o fluxo completo.'}</span></div></section>}
    <section className="plan-ladder">{sorted.map((plan)=>{const current=plan.id===planUsage.plan.id||plan.code===planUsage.plan.code;const info=planCopy[plan.code]||{headline:plan.name,description:'',bullets:[]};return <article className={`plan-tier ${plan.code==='STARTER'?'highlight':''} ${current?'current':''}`} key={plan.id}>{plan.code==='STARTER'&&<span className="plan-ribbon">Mais equilibrado</span>}<div className="plan-tier-head"><div><span className="plan-tier-name">{plan.name}</span><h2>{info.headline}</h2><p>{info.description}</p></div><div className="plan-tier-price"><strong>{currency.format(plan.monthlyPrice||0)}</strong><span>/mês</span></div></div><div className="plan-tier-features">{info.bullets.map((item)=><span key={item}><Check size={16}/>{item}</span>)}<span><Images size={16}/>{plan.imageLimitPerProduct===1?'1 foto por produto':`${plan.imageLimitPerProduct??'Fotos'} por produto`}</span>{planHasFeature(plan,'analytics')&&<span><BarChart3 size={16}/>Analytics habilitado</span>}{planHasFeature(plan,'finance')&&<span><WalletCards size={16}/>Financeiro habilitado</span>}</div><div className="plan-tier-action">{current&&<span className="plan-current-label"><Check size={15}/>Seu plano atual</span>}<button className={current?'secondary-button':'primary-button'} disabled={Boolean(busy)} onClick={()=>void generate(plan)}><QrCode size={17}/>{busy===plan.id?'Gerando PIX...':current?'Renovar mensalidade com PIX':'Assinar com PIX'}</button></div></article>})}</section>
    <section className="billing-explainer"><div><WalletCards size={22}/><div><h2>Mensalidade via PIX</h2><p>{billing?.provider==='asaas'?'A plataforma está preparada para PIX dinâmico. Quando o Asaas informar PAYMENT_RECEIVED, a renovação é automática.':'No modo atual, você paga para a chave da plataforma, envia o comprovante pelo WhatsApp e o Admin Master confirma a renovação.'}</p></div></div><span className={`automation-pill ${billing?.provider==='asaas'?'on':''}`}>{billing?.provider==='asaas'?'Renovação automática':'Conferência manual'}</span></section>
    {charge&&<section className="subscription-charge"><div className="subscription-charge-main"><span className="charge-icon"><QrCode/></span><div><h2>PIX gerado · {charge.plan.name}</h2><p>{currency.format(charge.payment.amount)} · vencimento {new Date(`${charge.payment.dueDate}T12:00:00`).toLocaleDateString('pt-BR')}</p></div></div>{charge.payment.pixQrBase64&&<img className="subscription-qr" src={`data:image/png;base64,${charge.payment.pixQrBase64}`} alt="QR Code PIX da mensalidade"/>}<div className="subscription-pix-data">{(charge.payment.pixPayload||charge.billing?.pixCopyPaste)&&<label>PIX copia e cola<div><input readOnly value={charge.payment.pixPayload||charge.billing?.pixCopyPaste||''}/><button type="button" onClick={()=>void copy(charge.payment.pixPayload||charge.billing?.pixCopyPaste||'')}><Copy size={16}/>Copiar</button></div></label>}{!charge.payment.pixPayload&&charge.billing?.pixKey&&<label>Chave PIX<div><input readOnly value={charge.billing.pixKey}/><button type="button" onClick={()=>void copy(charge.billing?.pixKey||'')}><Copy size={16}/>Copiar</button></div><small>{charge.billing.pixKeyType} · {charge.billing.pixHolderName}</small></label>}</div>{charge.payment.provider==='manual'&&charge.billing?.proofRequired&&<div className="proof-flow"><button className="whatsapp-proof-button" onClick={openProofWhatsApp}><MessageCircleMore size={18}/>Abrir WhatsApp e anexar comprovante</button>{!charge.payment.proofSentAt&&<button className="secondary-button" disabled={!proofOpened} onClick={()=>void confirmProofSent()}><Check size={17}/>Já enviei o comprovante</button>}{charge.payment.proofSentAt&&<div className="proof-sent-note"><Check size={16}/>Comprovante informado como enviado. Aguardando conferência.</div>}</div>}{charge.payment.provider==='asaas'&&<div className="auto-renew-note"><FileText size={17}/><span>Após o crédito ser confirmado pelo provedor, a assinatura é renovada sem precisar enviar comprovante.</span></div>}</section>}
  </>;
}
